---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gui-app
  namespace: dev
spec:
  selector:
    matchLabels:
      app: gui-test-app
  replicas: 1
  template:
    metadata:
      labels:
        app: gui-test-app
        group: api
    spec:
      hostname: gui-test-server
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
          - "gui-app.local"
      containers:
      - name: gui-test-app
        image: docker.io/amitkshirsagar13/gui-react-test-app
        ports:
        - name: app-port
          containerPort: 80
        resources:
          limits:
            cpu: "0.1"
            memory: "20Mi"
          requests:
            cpu: "0.05"
            memory: "10Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: gui-test-service
  namespace: dev
spec:
  ports:
  - port: 8080
    targetPort: app-port
    protocol: TCP
    name: app-port
  selector:
    app: gui-test-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gui-app-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  # http://gui-test-app.localtest.me/
  - host: gui-test-app.localtest.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gui-test-service
            port:
              number: 8080